baseURL = "https://help.stankoman.ru/"
languageCode = "ru-ru"
title = "Stankoman Help"
theme = "hugo-theme-techdoc"

[params]
description = "База знаний и инструкции"
menu_style = "slide-menu"
algolia_search_enable = false
dateformat = ":date_medium"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true

