baseURL = "https://help.stankoman.ru/"
languageCode = "ru-ru"
title = "Stankoman Help"
theme = "hugo-book"

[params]
description = "База знаний и инструкции"
BookTheme = "auto"
BookSearch = true
BookToC = true
BookSection = "*"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
